config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'sessions'
  }

  root 'welcome#index'

  match '/db_tables_information' => 'welcome#db_tables_information', via: :get, as: :db_tables_info

  resources :operations, except: :show do
    collection do
      get :fill_subcategory
      get :list_filter
    end
  end

  #TODO change(categories and subcategories) with sub-resources
  resources :categories
  resources :subcategories

  resources :finance_reports, only: :index

  match '/*path' => 'welcome#not_found', via: :get

end

app/models/subcategory.rb
# == Schema Information
#
# Table name: subcategories
#
#  id          :integer          not null, primary key
#  name        :string(255)      not null
#  created_at  :datetime
#  updated_at  :datetime
#  category_id :integer          not null
#

class Subcategory < ActiveRecord::Base

  belongs_to :category

  validates :name,
            format: {
                      with: /\A[a-zA-Zа-яА-я0-9\b \(\)]+\Z/,
                      message: 'Поле должно содержать буквы русского, латинского алфавита, цифры и знак "(" и ")"'
                    },
            presence: true

  scope :ordered_by_category, -> (category_id) { where('category_id = ?', category_id).order(:name) }

end

app/controllers/subcategories_controller.rb
#TODO use inheretedResources
class SubcategoriesController < ApplicationController

  PER_PAGE = 20

  def index
    @subcategories = current_user.subcategories.order('name').page(params[:page]).per PER_PAGE
  end

  def new
    @categories = Category.ordered_by_user(current_user)
    @subcategory = Subcategory.new
  end

  def create
    @categories = Category.ordered_by_user(current_user)
    @subcategory = Subcategory.new subcategory_params
    if @subcategory.save
      redirect_to subcategories_path, alert: t(:flash_notice)
    else
      render new_subcategory_path, alert: t(:flash_alert)
    end
  end

  def edit
    @subcategory = Subcategory.find params[:id]
    @categories = Category.ordered_by_user(current_user)
  end

  def update
    @categories = Category.ordered_by_user(current_user)
    @subcategory = Subcategory.find params[:id]
    if @subcategory.update subcategory_params
      redirect_to subcategories_path, alert: t(:flash_notice)
    else
      render edit_subcategory_path(@subcategory), alert: t(:flash_alert)
    end
  end

  def destroy
    @subcategory = Subcategory.find params[:id]
    @subcategory.destroy
    redirect_to subcategories_path
  end

private

  #TODO learn best practice with adding assocations
  def subcategory_params
    params.require(:subcategory).permit(:name, :category_id)
  end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.haml
= flash_messages
= flash_errors(@subcategory)
.object-form
  %div.object-form-header
    %h4= title_of_object_form(@subcategory)
  %div.object-form-content
    = form_for(@subcategory, html: {role: 'form', class: 'form-horizontal'}) do |f|
      .form-group
        .col-sm-3
          = f.label 'Категория', class: 'control-label'
        .col-sm-9
          = f.select :category_id, options_for_select(@categories.map {|e| [e.name, e.id]}, @subcategory.category_id), {}, class: 'form-control'
      .form-group
        .col-sm-3
          = f.label 'Наименование', class: 'control-label'
        .col-sm-9
          = f.text_field :name, class: 'form-control'
      .form-group
        .col-sm-12.text-right
          = f.submit 'Сохранить', role: 'button', class: 'btn btn-default'

app/views/subcategories/edit.html.haml
.container
  .row
    .col-md-12
      = flash_messages
  .row
    .col-md-6
      = render 'form'

app/views/subcategories/index.html.haml
.col-md-12
  .row
    .col-md-7
      .row
        .col-md-6
          = flash_messages
      .row
        .col-md-4
          %p
            %a.btn.btn-default{role: 'button', href: "#{new_subcategory_path}"}= t('common.ui.add_button')
        .col-md-8.text-right
          = paginate @subcategories
      .row
        .col-md-12
          %table.table.table-hover.table-bordered
            %thead
              %th №
              %th{colspan: '3'} Наименование
            %tbody
              - @subcategories.each_with_index do |subcategory, index|
                %tr
                  %td= index.next
                  %td.row-detail
                    %p= subcategory.name
                    %p
                      %span категория:
                      %span.subject= subcategory.category.name

                  %td.col-md-1.table-button
                    = link_to image_tag('edit-icon.png'), edit_subcategory_path(subcategory), title: 'Редактировать'
                  %td.col-md-1.table-button
                    = link_to image_tag('destroy-icon.png'), subcategory_path(subcategory), method: :delete, title: 'Удалить'

app/views/subcategories/new.html.haml
.container
  .row
    .col-md-12
      = flash_messages
  .row
    .col-md-6
      = render 'form'