config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'sessions'
  }

  root 'welcome#index'

  match '/db_tables_information' => 'welcome#db_tables_information', via: :get, as: :db_tables_info

  resources :operations, except: :show do
    collection do
      get :fill_subcategory
      get :list_filter
    end
  end

  #TODO change(categories and subcategories) with sub-resources
  resources :categories
  resources :subcategories

  resources :finance_reports, only: :index

  match '/*path' => 'welcome#not_found', via: :get

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer          not null
#

class Category < ActiveRecord::Base

  has_many :subcategories, dependent: :destroy
  belongs_to :user

  validates :name,
            format: {
                      with: /\A[a-zA-Zа-яА-я0-9\b \(\)]+\Z/,
                      message: 'Поле должно содержать буквы русского, латинского алфавита, цифры и знак "(" и ")"'
                    },
            presence: true

  scope :ordered_by_user, -> (user) { user.categories.order(:name) }
end

app/controllers/categories_controller.rb
#TODO use inheretedResources
class CategoriesController < ApplicationController

  PER_PAGE = 20

  def index
    @categories = Category.ordered_by_user(current_user).page(params[:page]).per PER_PAGE
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    @category.user = current_user
    if @category.save
      redirect_to categories_path, alert: t(:flash_notice)
    else
      render new_category_path, alert: t(:flash_alert)
    end
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    if @category.update category_params
      redirect_to categories_path, alert: t(:flash_notice)
    else
      render edit_category_path(@category), alert: t(:flash_alert)
    end
  end

  def destroy
    @category = Category.find params[:id]
    @category.destroy
    redirect_to categories_path
  end

private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= flash_messages
= flash_errors(@category)
.object-form
  %div.object-form-header
    %h4= title_of_object_form(@category)
  %div.object-form-content
    = form_for(@category, html: {role: 'form', class: 'form-horizontal'}) do |f|
      .form-group
        .col-sm-3
          = f.label 'Наименование', class: 'control-label'
        .col-sm-9
          = f.text_field :name, class: 'form-control'
      .form-group
        .col-sm-12.text-right
          = f.submit 'Сохранить', role: 'button', class: 'btn btn-default'

app/views/categories/edit.html.haml
.container
  .row
    .col-md-12
      = flash_messages
  .row
    .col-md-6
      = render 'form'

app/views/categories/index.html.haml
- #TODO create helper method to generate table list
.col-md-12
  .row
    .col-md-7
      .row
        .col-md-6
          = flash_messages
      .row
        .col-md-4
          %p
            %a.btn.btn-default{role: 'button', href: "#{new_category_path}"}= t('common.ui.add_button')
        .col-md-8.text-right
          = paginate @categories
      .row
        .col-md-12
          %table.table.table-hover.table-bordered
            %thead
              %th №
              %th{colspan: '3'} Наименование
            %tbody
              - @categories.each_with_index do |category, index|
                %tr
                  %td= index.next
                  %td= category.name
                  %td.col-md-1.table-button
                    = link_to image_tag('edit-icon.png'), edit_category_path(category), title: 'Редактировать'
                  %td.col-md-1.table-button
                    = link_to image_tag('destroy-icon.png'), category_path(category), method: :delete, title: 'Удалить'

app/views/categories/new.html.haml
.container
  .row
    .col-md-12
      = flash_messages
  .row
    .col-md-6
      = render 'form'