config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'sessions'
  }

  root 'welcome#index'

  match '/db_tables_information' => 'welcome#db_tables_information', via: :get, as: :db_tables_info

  resources :operations, except: :show do
    collection do
      get :fill_subcategory
      get :list_filter
    end
  end

  #TODO change(categories and subcategories) with sub-resources
  resources :categories
  resources :subcategories

  resources :finance_reports, only: :index

  match '/*path' => 'welcome#not_found', via: :get

end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title MYFINANCE - простой способ учета личных финансов
    %meta{ name: 'description', content: 'Примитивное приложение учитывающие личных финансов. Это не крутой приложение с огромными функциями и настройками, но с его помощью легко контролировать свои расходы или доходы, сколько на что потратил, сколько откуда получил.' }
    %meta{ name: 'keywords', content: 'My finance, личные финансы, простой способ учета, приход, расход'}
    %meta{ name: "google-site-verification", content: "1eAeNC4aaDfNUrwl1Fq29pnGxDqoZ_73jIXAX9pnfmA"}
    = favicon_link_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    - if Rails.env.production?
      = render 'shared/ga'
    = nav_bar :static => :top, fluid: true, brand: image_tag('app_icon.png') + ' MyFinance' do
      - if user_signed_in?
        = menu_group pull: :left do
          = menu_item "Операции", operations_path
          = menu_item "Категории", categories_path
          = menu_item "Субкатегории", subcategories_path
          = menu_item "Информация о таблиц БД", db_tables_info_path if admin_user?
        = menu_group pull: :right do
          = menu_item current_user.email
          = menu_item "Выйти", destroy_user_session_path, method: :delete

      - else
        = menu_group :pull => :right do
          = menu_item "Войти", new_user_session_path
          = menu_item "Регистрация", new_user_registration_path

    .container-fluid
      .row
        .col-md-12
          = yield

    = nav_bar :static => :bottom, fluid: true do
      .text-center
        %div
          %span{style: 'color: black'} ©2015
          %span{style: 'color: blue'} Dilshod Samatov
        %div
          %span{style: 'font-size: 12px;'} email:- samatov.dilshod@gmail.com

    :javascript
      //TODO if alert more than one, this get error
      $(document).ready( function(){
        alertContent = $('div.alert');
        if(alertContent.length){
           new PNotify({
              title: 'Сообщение!',
              text: alertContent.data('message') ? alertContent.data('message') : 'Ошибка',
              type: 'info',
              animate_speed: 'fast',
              delay: 1500,
              icon: true
          })
        }
      });