config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'sessions'
  }

  root 'welcome#index'

  match '/db_tables_information' => 'welcome#db_tables_information', via: :get, as: :db_tables_info

  resources :operations, except: :show do
    collection do
      get :fill_subcategory
      get :list_filter
    end
  end

  #TODO change(categories and subcategories) with sub-resources
  resources :categories
  resources :subcategories

  resources :finance_reports, only: :index

  match '/*path' => 'welcome#not_found', via: :get

end

app/models/operation.rb
# == Schema Information
#
# Table name: operations
#
#  id             :integer          not null, primary key
#  date           :date             not null
#  sum            :decimal(15, 2)   not null
#  category_id    :integer          not null
#  subcategory_id :integer
#  comment        :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  source         :integer          not null
#  user_id        :integer          not null
#

class Operation < ActiveRecord::Base

  SOURCES = [['Наличка', 1], ['Пл.карта', 2]]

  belongs_to :category
  belongs_to :subcategory
  belongs_to :user

  validates_presence_of :date, :sum, :source, :category_id

  scope :finance_report, -> {
    self.includes(:category, :subcategory).
          group(:category_id, :subcategory_id).
          select("category_id, subcategory_id, sum(sum) as sum").
          where('sum < 0')
  }

  scope :by_user, lambda {|user_id|
    where('user_id = ?', user_id)
  }

  def self.get_by user_id, params
    filter_string = ''
    date_begin = params[:date_begin]
    date_end = params[:date_end]

    query_conditions = { text: 'user_id = :user_id', params: { user_id: user_id } }

    if date_begin.blank? || date_end.blank?
    else
      query_conditions[:text] << ' and date between :date_begin and :date_end'
      query_conditions[:params][:date_begin] = date_begin.to_date
      query_conditions[:params][:date_end] = date_end.to_date
      filter_string = "Дата между '#{date_begin}' и '#{date_end}'"
    end

    search_source_name = SOURCES.select{|e| e.second.to_s == params[:source]}.first if params[:source]
    source_name = search_source_name.first if search_source_name

    params_arr = %W{source category subcategory}
    params_arr.each do |e|
      unless params[e.to_sym].blank?
        case e.to_sym
          when :source
            query_conditions[:text] << ' and source = :source '
            query_conditions[:params][:source] = params[:source]
            filter_string << " источник='#{source_name}'"
          when :category
            query_conditions[:text] << ' and category_id = :category_id '
            query_conditions[:params][:category_id] = params[:category]
            filter_string << " Категория='#{Category.find(params[:category]).name}'"
          when :subcategory
            query_conditions[:text] << ' and subcategory_id = :subcategory_id '
            query_conditions[:params][:subcategory_id] = params[:subcategory]
            filter_string << " Субкатегория='#{Subcategory.find(params[:subcategory]).name}'"
        end
      end
    end

    return where([query_conditions[:text], query_conditions[:params]]).order('date desc'), filter_string
  end

  def source_name
    result = SOURCES.select do |e|
      e.second == self.source
    end
    result.first.first
  end

end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController

  respond_to :json, only: :fill_subcategory

  PER_PAGE = 24

  def index
    @filter_string = ''
    if params.key? :filter
      @operations, @filter_string = Operation.get_by current_user.id, params[:filter]
    else
      @operations = current_user.operations.order('date desc')
    end
    @calculations = build_calculation_hash
    @operations = @operations.page(params[:page]).per PER_PAGE
  end

  def new
    @operation = Operation.new
    build_variables
  end

  def create
    @operation = Operation.new operation_params
    @operation.user = current_user
    if @operation.save
      redirect_to operations_path, notice: t(:flash_notice)
    else
      build_variables
      render :new
    end
  end

  def edit
    @operation = Operation.find params[:id]
    build_variables @operation.category_id
  end

  def update
    @operation = Operation.find params[:id]
    if @operation.update operation_params
      redirect_to operations_path, notice: t(:flash_notice)
    else
      build_variables @operation.category_id
      render :edit
    end
  end

  def destroy
    @operation = Operation.find params[:id]
    @operation.destroy
    redirect_to operations_path
  end

  #TODO sepatare controller for selects
  def fill_subcategory
    @select_data = Subcategory.ordered_by_category params[:category_id]
  end

  def list_filter
    build_variables
  end

private

  #TODO learn best practice with adding assocations
  def operation_params
    params.require(:operation)
      .permit(:date,
              :sum,
              :source,
              :category_id,
              :subcategory_id,
              :comment)
  end

  def build_variables category_id = nil
    @categories = Category.ordered_by_user current_user
    if @categories.size == 0
      @subcategories = []
    else
      @subcategories = Subcategory.ordered_by_category(category_id.blank? ? @categories.first.id : category_id)
    end
  end

  def build_calculation_hash
    incoming_cash_sum = @operations.where('sum > 0 and source = 1').sum(:sum).to_f
    incoming_plastic_sum = @operations.where('sum > 0 and source = 2').sum(:sum).to_f

    expense_cash_sum = @operations.where('sum < 0 and source = 1').sum(:sum).to_f
    expense_plastic_sum = @operations.where('sum < 0 and source = 2').sum(:sum).to_f

    h = {
          incoming: incoming_cash_sum + incoming_plastic_sum,
          expense: expense_cash_sum + expense_plastic_sum,
          difference: (incoming_cash_sum + incoming_plastic_sum) - (expense_cash_sum + expense_plastic_sum)*-1,
          incoming_details: { cash:  incoming_cash_sum, card: incoming_plastic_sum },
          expense_details: { cash:  expense_cash_sum, card: expense_plastic_sum}
        }
    return h
  end

end

app/helpers/operations_helper.rb
module OperationsHelper

  def colorize_filter_string str
    str.gsub /'[А-Яа-яA-Za-z0-9\-\b \(\)]+'/ do |repl|
      "' <span class='filter-string'>#{repl[1..-2]}</span> '"
    end
  end

  def total_currence_details detail
    cash = number_to_currency(detail[:cash], unit: '')
    card = number_to_currency(detail[:card], unit: '')
    "Наличный: #{cash} \nПластик: #{card}" if not_source_filter? && cash.to_i + card.to_i != 0
  end

private

  def not_source_filter?
    params.try(:[], :filter).try(:[], :source).blank?
  end

end

app/views/operations/_form.html.haml
= flash_messages
= flash_errors(@operation)
.object-form
  %div.object-form-header
    %h4= title_of_object_form(@operation)
  %div.object-form-content
    = form_for(@operation, html: {role: 'form', class: 'form-horizontal'}) do |f|
      .row
        .col-sm-4
          = f.label 'Дата', class: 'control-label'
        .col-sm-8
          .form-group

            .input-group
              - if @operation.new_record?
                = f.text_field :date, value: l(Date.today), class: 'form-control', role: 'datepicker'
              - else
                = f.text_field :date, value: l(@operation.date), class: 'form-control', role: 'datepicker'
      .row
        .col-sm-4
          = f.label 'Сумма', class: 'control-label'
        .col-sm-6
          .form-group
            .input-group
              = f.text_field :sum, class: 'form-control text-right', role: 'calculator-source-field'
              .input-group-addon.pad-none
                = link_to image_tag('calc.png'), nil, role: 'open-calculator', class: 'addon-image', title: 'Калькулятор'
      .row
        .col-sm-4
          = f.label 'Источник', class: 'control-label'
        .col-sm-8
          .form-group
            .input-group
              = f.select :source, Operation::SOURCES, {}, class: 'form-control'
      .row
        .col-sm-4
          = f.label 'Категория', class: 'control-label'
        .col-sm-8
          .form-group
            .input-group
              = f.select :category_id, options_for_select(@categories.map {|e| [e.name, e.id]}, @operation.category_id), {}, class: 'form-control', role: 'category'
      .row
        .col-sm-4
          = f.label 'Субкатегории', class: 'control-label'
        .col-sm-8
          .form-group
            .input-group
              = f.select :subcategory_id, options_for_select(@subcategories.map {|e| [e.name, e.id]}, @operation.subcategory_id), {}, class: 'form-control', role: 'subcategory'
      .row
        .col-sm-4
          = f.label 'Комментарии', class: 'control-label'
        .col-sm-8
          .form-group
            .input-group
              = f.text_area :comment, class: 'form-control', cols: '40'
      .row
        .col-sm-11
          .form-group.text-right
            = f.submit 'Сохранить', role: 'button', class: 'btn btn-default'

app/views/operations/edit.html.haml
.container
  .row
    .col-md-6
      = render 'form'

app/views/operations/index.html.haml
.col-md-10
  .row
    .col-md-6
      = flash_messages
  .row
    .col-md-8
      .currency-info
        .row
          .col-md-5.balance
            .row
              .col-md-7
                %p= t('ui.operations.rest_of_plastic_card')
              .col-md-5
                %p= "______"
            .row
              .col-md-7
                %p= t('ui.operations.rest_of_crash')
              .col-md-5
                %p= "______"
          .col-md-5.revs
            .row
              .col-md-4
                %p= t('ui.operations.incoming')
              .col-md-4.text-right
                %p{ 'data-toggle' => "tooltip",
                    'data-placement' => "bottom",
                    'title' => total_currence_details(@calculations[:incoming_details])}
                  = number_to_currency @calculations[:incoming], unit: ''
            .row
              .col-md-4
                %p= t('ui.operations.outgoing')
              .col-md-4.text-right
                %p{ 'data-toggle' => "tooltip",
                    'data-placement' => 'bottom',
                    'title' => total_currence_details(@calculations[:expense_details])}
                  = number_to_currency @calculations[:expense], unit: ''
            .row
              .col-md-4
                %p= t('ui.operations.difference')
              .col-md-4.text-right
                %p= number_to_currency @calculations[:difference], unit: ''
  .row
    .col-md-6
      .row
        .col-md-12
          %p
            %a.btn.btn-default{role: 'button', href: "#{new_operation_path}"}= t('common.ui.add_button')
            %a.btn.btn-default{role: 'button', href: "#{list_filter_operations_path}"}= t('common.ui.filter_button')
      .row
        .col-md-12
          %p
            - unless @filter_string.blank?
              = "#{t('common.ui.filter_label_string')}: #{colorize_filter_string(@filter_string)}".html_safe

    .col-md-6.text-right
      = paginate @operations
  .row
    .col-md-12
      %table.table.table-hover.table-bordered
        %thead
          %th №
          %th= t('ui.operations.table.column_date')
          %th= t('ui.operations.table.column_sum')
          %th= t('ui.operations.table.column_transcript')
          %th{colspan: '3'}= t('ui.operations.table.column_note')
        %tbody
          - @operations.each_with_index do |operation, index|
            %tr
              %td= index.next
              %td= l(operation.date)
              %td.row-detail
                %p.text-right= number_to_currency(operation.sum, unit: '')
                %p
                  %span= "#{t('ui.operations.source_type')}:"
                  %span.subject= operation.source_name
              %td.row-detail
                %p= operation.subcategory.name if operation.subcategory
                %p
                  %span= "#{t('ui.operations.category_type')}:"
                  %span.subject= operation.category.name
              %td= operation.comment
              %td.table-button= link_to image_tag('edit-icon.png'), edit_operation_path(operation), title: 'Редактировать'
              %td.table-button= link_to image_tag('destroy-icon.png'), operation_path(operation), method: :delete, title: 'Удалить'

app/views/operations/list_filter.html.haml
.container
  .row
    .col-md-7
      .object-form
        %div.object-form-header
          %h4 Фильтрировать записи
        %div.object-form-content
          = form_tag operations_path, {role: 'form', class: 'form-horizontal', method: :get} do
            .form-group
              .col-sm-2
                = label :filter, :date_begin, 'Период с', class: 'control-label'
              .col-sm-3
                = text_field :filter, :date_begin, class: 'form-control', readonly: true, role: 'datepicker-begin', value: l(Date.today)
              .col-sm-1
                = label :filter, :date_end, 'по', class: 'control-label'
              .col-sm-3
                = text_field :filter, :date_end, class: 'form-control', readonly: true, role: 'datepicker-end', value: l(Date.today)
              .col-sm-1
                = button_tag '...', type: 'button', role: 'open-financical-period-selector', title: 'Выбор периода'
            .form-group
              .col-sm-2
                = label :filter, :source, 'Источник', class: 'control-label'
              .col-sm-5
                = select :filter, :source, Operation::SOURCES, {include_blank: true}, class: 'form-control'
            .form-group
              .col-sm-2
                = label :filter, :category, 'Категория', class: 'control-label'
              .col-sm-5
                = select :filter, :category, options_for_select(@categories.map {|e| [e.name, e.id]}), {include_blank: true}, class: 'form-control', role: 'category', data: {filter: true}
            .form-group
              .col-sm-2
                = label :filter, :subcategory, 'Субкатегории', class: 'control-label'
              .col-sm-5
                = select :filter, :subcategory, options_for_select(@subcategories.map {|e| [e.name, e.id]}), {include_blank: true}, class: 'form-control', role: 'subcategory'
            .form-group
              .col-sm-12.text-right
                = submit_tag 'Выполнить', role: 'button', class: 'btn btn-default'

app/views/operations/new.html.haml
.container
  .row
    .col-md-7
      = render 'form'